### ISSUE TITLE
CPU aes instruction set?

### ISSUE THREAD

**Issue by hellegaard1** [GL513/cpuminer-in-termux#2]
Any way in making this use aes instructions? Doesn't see that aes is supported even though it is.

**Comment by GL513** [comment]
> Any way in making this use aes instructions? Doesn't see that aes is supported even though it is. 

Hey, sorry for getting to you late. You should be able to tell if you device supports aes or not by the title that says "Algo features"

![Screenshot_20211125-203817.png](https://user-images.githubusercontent.com/83085846/143514080-f2876a9a-fe98-4338-8038-ace6265d4aad.png)

**Comment by hellegaard1** [comment]
I see that, which mine does. The "starting miner with no optimizations" is what I was speaking of. Mining on PC states starting miner with Avx2? I assumed aes would be stated there instead for mobile.

**Comment by GL513** [comment]
> I see that, which mine does. The "starting miner with no optimizations" is what I was speaking of. Mining on PC states starting miner with Avx2? I assumed aes would be stated there instead for mobile.
 
If your android cpu supports it, it should say both avx and aes, if not, it will probably only say avx. You can probably look up your cpu and see if it supports aes or not. Most modern CPUs do.
